declare -a PKGS

PKGS=()
PKGS+=(sway)
PKGS+=(swaybg)
PKGS+=(swayidle)
PKGS+=(waybar)
PKGS+=(emacs-nox)
PKGS+=(fzf)
PKGS+=(wl-clipboard)
PKGS+=(kbd)
PKGS+=(git)
PKGS+=(x11-utils)
PKGS+=(netsurf-fb)
PKGS+=(netsurf-gtk)
PKGS+=(tmux)
PKGS+=(neovim)
PKGS+=(chafa)
PKGS+=(imv)
PKGS+=(octave)
PKGS+=(maxima)
PKGS+=(wxmaxima)
PKGS+=(bsdgames)
PKGS+=(wev)
PKGS+=(brightnessctl)
PKGS+=(fonts-recommended)
PKGS+=(fonts-noto-color-emoji)
PKGS+=(fonts-symbola)
PKGS+=(ttf-ancient-fonts)
PKGS+=(grim)
PKGS+=(neofetch)
PKGS+=(firefox-esr)
PKGS+=(blueman)
PKGS+=(pmount)
PKGS+=(bat)
PKGS+=(delta)

sudo apt install "${PKGS[@]}"
